### ISSUE TITLE
Crash when writing log file to disk on Android 24 (7.0) 

### ISSUE THREAD

**Issue by dpad85** [ACINQ/phoenix-kmm#126]
Using `org.kodein.memory:kodein-memory-files:0.7.0`, commit 3a4c41f on API 24 aka Android 7.0 (and maybe later). Does not happen on Android 30.

https://github.com/ACINQ/phoenix-kmm/blob/2149e623b43398143740679fb8c1601c9a1e075e/phoenix-shared/src/commonMain/kotlin/fr.acinq.phoenix/utils/LogMemory.kt#L86-L88

When writing the file to disk this exception is raised:

```
2021-03-08 21:23:49.750 7803-7819/fr.acinq.phoenix.android E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: fr.acinq.phoenix.android, PID: 7803
    java.io.FileNotFoundException: /data/user/0/fr.acinq.phoenix.android/files/logs/2021-03-08.txt (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.kodein.memory.file.FilesJvmKt.openWriteableFile-pJkIwUA(filesJvm.kt:24)
        at fr.acinq.phoenix.utils.LogMemoryKt$writeLogs$1.invokeSuspend(LogMemory.kt:86)
...
```

If I manually create the `logs` directory on that path, kodein-memory infinitely loops on `FilesKt.createDirs` and the app ends up crashing.

```
2021-03-08 21:23:01.727 7701-7701/? E/AndroidRuntime:     at org.kodein.memory.file.FilesKt.createDirs-lUIXZXY(files.kt:44)
        at org.kodein.memory.file.FilesKt.createDirs-lUIXZXY(files.kt:44)
        at org.kodein.memory.file.FilesKt.createDirs-lUIXZXY(files.kt:44)
```

Any ideas @SalomonBrys @romainbsl ?

**Comment by dpad85** [comment]
This repository is obsolete and is replaced by https://github.com/ACINQ/phoenix.
